on:
  workflow_dispatch:

name: Test Analyze Mode

permissions:
  packages: write
  contents: read
  actions: read

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Start Falco
      uses: falcosecurity/falco-actions/start@main
      with:
        mode: analyze
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
        echo ${{ github.workspace }}
        cat ${{ github.workspace }}/pwn.txt
    
    - name: Read Sensitive File
      run: |
        sleep 3
        docker run --rm --privileged ubuntu cat /etc/shadow
        sleep 3

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop@main
      with:
        mode: analyze
        verbose: true

  analyze:
    runs-on: ubuntu-latest
    needs: test-falco
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: falcosecurity/falco-actions/analyze@ddcff83af077b30af70f188ba7b5446c98041446
      with:
        falco-version: '0.40.0'
