name: Falco Supply Chain Attack Detection

on:
  repository_dispatch:
    types: [falco-detection]

permissions:
  security-events: write

jobs:
  detect-supply-chain-attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run build with Falco monitoring
        run: docker-compose -f falco-docker-compose.yaml up --abort-on-container-exit

      - name: Upload Falco logs
        uses: actions/upload-artifact@v4
        with:
          name: falco-logs
          path: ./falco_logs

      - name: Check for Falco alerts
        run: |
          if grep -q "Suspicious" ./falco_logs/falco.log; then
            echo "Falco detected suspicious behavior"
            exit 1
          else
            echo "No suspicious activity detected"
          fi