name: Falco Detection

on:
    workflow_dispatch:

jobs:
  falco-security-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Start Falco
      uses: falcosecurity/falco-actions/start@e23d661998204b25988e4655899418e46924a68b
      with:
        mode: analyze
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${OWNER}/vulnerable-app:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/vulnerable-app:latest    
   

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop@e23d661998204b25988e4655899418e46924a68b
      with:
        mode: analyze
  
  analyze-falco-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: falcosecurity/falco-actions/analyze@e23d661998204b25988e4655899418e46924a68b
      with:
        falco-version: '0.39.0'
