on:
  workflow_dispatch:

name: Falco Detection Final

permissions:
  packages: write
  contents: read
  actions: read

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Do Everything
      run: |
        sed "s|\\${{ github\\.workspace }}|${{ github.workspace }}|g" ${{ github.workspace }}/falco_rules/custom_rules.yaml > ${{ github.workspace }}/falco_rules/custom_rules.yaml
        cat ${{ github.workspace }}/falco_rules/custom_rules.yaml
        exit 0
        # echo ${{ github.workspace }}
        docker run --rm -d \
          --name falco \
          --privileged \
          -v /tmp:/tmp \
          -v /var/run/docker.sock:/host/var/run/docker.sock \
          -v /proc:/host/proc:ro \
          -v /etc:/host/etc:ro \
          -v ${{ github.workspace }}:/javascript:rw \
          -v ${{ github.workspace }}/falco_rules/custom_rules.yaml:/etc/falco/rules.d/custom_rules.yaml \
          falcosecurity/falco:latest falco -o "json_output=true" -o "file_output.enabled=true" -o "file_output.keep_alive=false" -o "file_output.filename=/tmp/falco_events.json" -o "engine.kind=modern_ebpf" -o base_syscalls.all=true

        for i in {1..30}; do
          if docker ps --filter "name=falco" --filter "status=running" | grep -q falco; then
            echo "Falco is running!!!!!!!!!"
            break
          fi
          echo "Waiting...."
          sleep 1
        done
        
        docker run --rm -d --name sysdig --privileged \
          -v /var/run/docker.sock:/host/var/run/docker.sock \
          -v /dev:/host/dev -v /proc:/host/proc:ro \
          -v /boot:/host/boot:ro \
          -v /lib/modules:/host/lib/modules:ro \
          -v /home/garou/sandbox/javascript:/javascript:rw \
          -v /usr:/host/usr:ro \
          -v /tmp:/tmp \
          --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/capture.scap --snaplen=256 "not evt.type in (switch)"

        for i in {1..30}; do
          if docker ps --filter "name=sysdig" --filter "status=running" | grep -q sysdig; then
            echo "Sysdig is running!!!!!!!!!"
            break
          fi
          echo "Waiting...."
          sleep 1
        done

        echo "Stato processi: "
        docker ps -a > a.txt
        cat a.txt

        cd ${{ github.workspace }}
        npm install
        [[ -f /tmp/falco_events.json ]] && cat /tmp/falco_events.json
        docker stop falco
        docker stop sysdig
        
        # cat ${{ github.workspace }}/falco_rules/custom_rules.yaml
