name: Falco Supply Chain Attack Detection

on:
  repository_dispatch:
    types: [falco-detection]

jobs:
  falco-security-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Start Falco
      uses: falcosecurity/falco-actions/start
      with:
        mode: analyze
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/vulnerable-app:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/vulnerable-app:latest    
   

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop
      with:
        mode: analyze
  
  analyze-falco-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: falcosecurity/falco-actions/analyze
      with:
        falco-version: '0.39.0'