name: SCA + Forensic Logging + Splunk HEC

on:
  repository_dispatch:
    types: [snyk-scan-forensic]

permissions:
  security-events: write

env:
  SPLUNK_HEC_ENDPOINT: "https://192.168.1.131:8088"
  SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}

jobs:
  snyk:
    runs-on: self-hosted

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Record checksums BEFORE install
        run: |
          find . -type f ! -path './node_modules/*' -exec sha256sum {} \; | sort > checksums-before.txt
        shell: bash
      
      - name: Install dependencies
        run: |
          echo "=== npm install $(date --iso-8601=seconds) ===" | tee install.log
          npm install 2>&1 | tee -a install.log

      - name: Record checksums AFTER install
        run: |
          find . -type f ! -path './node_modules/*' -exec sha256sum {} \; | sort > checksums-after.txt
        shell: bash

      - name: Compare checksums and alert on mismatch
        run: |
          if ! diff --brief checksums-before.txt checksums-after.txt >/dev/null; then
            echo "File checksum mismatch detected after npm install" >&2
            payload=$(
              jq -n \
                --arg job     "$GITHUB_JOB" \
                --arg run     "$GITHUB_RUN_ID" \
                --arg url     "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
                '{ 
                  event: {
                    level:   "critical",
                    message: "Checksum mismatch detected after npm install, a file has been overwritten",
                    job:     $job,
                    run_id:  $run,
                    url:     $url
                  },
                  sourcetype: "github:actions:forensics"
                }'
            )
            # Send to Splunk HEC
            curl -k "${SPLUNK_HEC_ENDPOINT}/services/collector/event" \
              -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "$payload"
            # In a real environment, uncomment the exit and comment the echo
            # exit 1
            echo "Checksum mismatch!"
          else
            echo "Checksums match; proceeding."
          fi
        shell: bash

      - name: Archive installation logs and checksum files
        uses: actions/upload-artifact@v4
        with:
          name: install-and-checksums-${{ github.run_id }}
          path: |
            install.log
            checksums-before.txt
            checksums-after.txt
      
      - name: Forensic Environment Snapshot
        run: |
          mkdir -p forensic
          uname -a > forensic/os.txt
          npm ls --all > forensic/npm-packages.txt
          env > forensic/env.txt
        shell: bash

      - name: Upload forensic snapshot
        uses: actions/upload-artifact@v4
        with:
          name: forensic-snapshot-${{ github.run_id }}
          path: forensic/

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: npm-install-log-${{ github.run_id }}
          path: install.log

      - name: Run Snyk SCA and output SARIF (and log)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true

      - name: Upload SARIF
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif-${{ github.run_id }}
          path: snyk.sarif

      - name: Upload SARIF to GitHub (Code Scanning)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Forward metadata (JSON) to Splunk HEC
        run: |
          # Build a small JSON payload with key GitHub context + forensic summary
          jq -n --arg run_id "$GITHUB_RUN_ID" \
                --arg repo    "$GITHUB_REPOSITORY" \
                --arg actor   "$GITHUB_ACTOR" \
                --arg commit  "$GITHUB_SHA" \
                --arg ref     "$GITHUB_REF" \
                --arg time "$(date +%s)" \
            '{
               event: {
                 run_id: $run_id,
                 repository: $repo,
                 actor: $actor,
                 commit: $commit,
                 ref: $ref,
                 timestamp: $time
               },
               sourcetype: "github:actions:snyk"
             }' \
          | gzip | \
          curl -k "$SPLUNK_HEC_ENDPOINT/services/collector" \
            -H "Authorization: Splunk $SPLUNK_HEC_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Content-Encoding: gzip" \
            --data-binary @-
