name: SCA with Snyk + Splunk Forwarding

on:
  workflow_dispatch:

permissions:
  security-events: write

env:
  # Make HEC endpoint and token available in all steps
  SPLUNK_HEC_ENDPOINT: "https://192.168.1.131:8088/services/collector"
  SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (and log)
        run: |
          echo "=== npm install ===" | tee -a workflow.log
          npm install 2>&1 | tee -a workflow.log

      - name: Run Snyk SCA and output SARIF (and log)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true

      - name: Print SARIF to log
        run: cat snyk.sarif | tee -a workflow.log

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Forward logs and metadata to Splunk
        run: |
          payload=$(
            jq -n \
              --arg run_id "$GITHUB_RUN_ID" \
              --arg repo "$GITHUB_REPOSITORY" \
              --arg workflow "$GITHUB_WORKFLOW" \
              --arg logs "$(sed 's/"/\\"/g' workflow.log)" \
              '{ 
                 event: {
                   run_id: $run_id,
                   repository: $repo,
                   workflow: $workflow,
                   logs: $logs
                 },
                 sourcetype: "github:actions:sca"
               }'
          )

          curl -k "${SPLUNK_HEC_ENDPOINT}" \
            -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "$payload"
