name: Manual IoC Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ioc-scan
        run: pip install ioc-scan

      - name: Run IoC Scanner
        run: |
          # run against your repo root, pointing to your IoC lists
          ioc-scan \
            --file ./iocs/hashes.txt \
            --file ./iocs/domains.txt \
            --file ./iocs/ips.txt \
            --target .