name: IOC Finder Scan

on:
  repository_dispatch:
    types: [ioc-scan]

jobs:
  scan:
    name: Run IOC Matcher
    runs-on: [self-hosted, linux]

    env:
      MISP_URL:     ${{ secrets.MISP_URL }}
      MISP_API_KEY: ${{ secrets.MISP_API_KEY }}
      INPUT_FOLDER: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ioc-finder pymisp

      - name: Run IOC Matcher
        run: |
          mkdir -p output
          python ${{ github.workspace }}/utility/ioc_matcher.py --input-folder "$INPUT_FOLDER" --misp-url "$MISP_URL" --misp-key "$MISP_API_KEY" > output/report.md
        continue-on-error: true

      - name: Upload full report artifact
        uses: actions/upload-artifact@v4
        with:
          name: ioc-report-md
          path: output/report.md

      - name: Publish report to Summary
        run: |
          echo "## :warning: IOC Matcher Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          tail -n +2 output/report.md >> $GITHUB_STEP_SUMMARY
