name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cni: bridge
          container-runtime: containerd
          cpus: 2
          memory: 4096m
          start-args: '--wait=apiserver'

      - name: Set up the microservice
        run: |
          eval $(minikube -p minikube docker-env)
          export DOCKER_BUILDKIT=0
          docker build -t microservizio-js:v1 .
          kubectl apply -f microservizio-js-deployment.yaml
          kubectl rollout status deployment/microservizio-js --timeout=120s
          for i in {1..30}; do
            if kubectl get svc microservizio-js-service; then
              echo "Service is ready."
              break
            fi
            echo "Waiting for service..."
            sleep 5
          done

      #- name: Get Service URL
      #  id: service-url
      #  run: |
      #    echo "SERVICE_URL=$(minikube service microservizio-js-service --url)" >> $GITHUB_ENV
      #    echo $GITHUB_ENV
      - name: Port forward microservice
        run: kubectl port-forward service/microservizio-js-service 3000:3000 &

      - name: Wait for service to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for service..."
            sleep 2
          done
      
      - name: Run ZAP Full Scan Manually with Host Network
        run: |
          docker run --rm --network=host \
            -v $(pwd):/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://localhost:3000 -a

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          path: zap-report.html

      - name: Cleanup
        if: always()
        run: |
          kubectl delete -f microservizio-js-deployment.yaml
