name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cni: bridge
          container-runtime: containerd
          cpus: 2
          memory: 4096m
          start-args: '--wait=apiserver'

      - name: Set up the microservice
        run: |
          eval $(minikube -p minikube docker-env)
          export DOCKER_BUILDKIT=0
          docker build -t microservizio-js:v1 .
          kubectl apply -f microservizio-js-deployment.yaml
          kubectl rollout status deployment/microservizio-js --timeout=120s
          for i in {1..30}; do
            if kubectl get svc microservizio-js-service; then
              echo "Service is ready."
              break
            fi
            echo "Waiting for service..."
            sleep 5
          done

      - name: Get Minikube IP
        id: minikube-ip
        run: |
          MINIKUBE_IP=$(minikube ip)
          echo "MINIKUBE_IP=$MINIKUBE_IP" >> $GITHUB_ENV
          echo "Minikube IP is: $MINIKUBE_IP"

      - name: Port forward microservice
        run: minikube tunnel &

      - name: Wait for service to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://192.168.49.2:30000 > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for service..."
            sleep 2
          done

      - name: Run ZAP Full Scan with Minikube IP
        run: |
          docker run --rm --network=host \
          -v $(pwd):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py -t http://192.168.49.2:3000 -a

      - name: Create GitHub Issue if Vulnerabilities Found
        if: failure()  # This only runs if the ZAP scan fails (i.e., finds vulnerabilities)
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title":"ZAP Security Issues Detected","body":"ZAP Full Scan detected vulnerabilities on the microservice."}' \
            https://api.github.com/repos/${{ github.repository }}/issues
          
      - name: Cleanup
        if: always()
        run: |
          kubectl delete -f microservizio-js-deployment.yaml
