name: DAST with OWASP ZAP

on:
  repository_dispatch:
    types: [dast-zap]

permissions:
  contents: write
  issues: write

jobs:
  build-deploy-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cni: bridge
          container-runtime: docker
          cpus: 2
          memory: 4096m
          start-args: '--wait=apiserver'

      - name: Build Docker image in Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t microservizio-js:v1 .
          docker images

      - name: Deploy to Minikube
        run: |
          kubectl apply -f microservizio-js-deployment.yaml
          kubectl rollout status deployment/microservizio-js --timeout=120s

      - name: Start Minikube tunnel in background
        run: |
          sudo nohup minikube tunnel > /tmp/tunnel.log 2>&1 &
          sleep 5

      - name: Wait for EXTERNAL-IP
        id: wait_external_ip
        run: |
          for i in {1..30}; do
            EXTERNAL_IP=$(kubectl get svc microservizio-js-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ ! -z "$EXTERNAL_IP" ]]; then
              echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
              echo "External IP assigned: $EXTERNAL_IP"
              break
            fi
            echo "Waiting for external IP..."
            sleep 5
          done
          if [[ -z "$EXTERNAL_IP" ]]; then
            echo "EXTERNAL-IP not assigned in time." >&2
            exit 1
          fi

      - name: Wait for service to be available
        run: |
          for i in {1..10}; do
            if curl -s http://$EXTERNAL_IP:3000 >/dev/null; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for service to be available..."
            sleep 5
          done
          echo "Service did not become available in time." >&2
          exit 1

      - name: Run OWASP ZAP Full Scan
        id: zap_scan
        continue-on-error: true
        run: |
          docker run --rm --network=host \
            -v $(pwd):/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://$EXTERNAL_IP:3000 -a -r zap_report.html
          echo "ZAP_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Create GitHub Issue if Vulnerabilities Found
        if: env.ZAP_EXIT_CODE != '0'
        run: |
          BODY=$(cat zap_report.html | base64)
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"title\":\"ZAP Security Issues Detected\",\"body\":\"ZAP Full Scan detected vulnerabilities on the microservice. See attached report (base64-encoded):\n\n$BODY\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues

      - name: Cleanup
        if: always()
        run: |
          kubectl delete -f microservizio-js-deployment.yaml || true
