name: YARA Obfuscation Scan

on:
  workflow_dispatch:

jobs:
  yara-scan:
    name: Scan for Obfuscated (Base64) Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install YARA
        run: |
          sudo apt-get update
          sudo apt-get install -y yara

      - name: Run YARA scan
        id: scan
        run: |
          yara -r ${{ github.workspace }}/yara_rules/base64_obfuscation.yar .

      #- name: Fail if obfuscation detected
      #  if: steps.scan.outcome == 'success' && steps.scan.outputs.stdout != ''
        #run: |
          #echo "::error ::Obfuscated (Base64) code detected by YARA. Please review the matches above."
          #exit 1