name: YARA Obfuscation Scan

on:
  workflow_dispatch:

jobs:
  yara-scan:
    name: Scan for Obfuscated (Base64) Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install YARA
        run: |
          sudo apt-get update
          sudo apt-get install -y yara

      - name: Run YARA scan (exclude .git folder)
        id: scan
        run: |
          yara -r yara_rules/base64_obfuscation.yar . > results.txt || true
          echo "Filtered YARA scan results (excluding .git):"
          grep -v "git" results.txt || echo "No matches found."