name: YARA Obfuscation Scan

on:
  workflow_dispatch:

jobs:
  yara-scan:
    name: Scan for Obfuscated (Base64) Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install YARA
        run: |
          sudo apt-get update
          sudo apt-get install -y yara

      - name: Run YARA scan (exclude .git folder)
      id: scan
      run: |
        mkdir -p yara_output
        OUTPUT_FILE=yara_output/results.txt
        # Run YARA and store results in a file
        yara -r yara_rules/base64_obfuscation.yar > "$OUTPUT_FILE" || true
        echo "Filtered YARA scan results (excluding .git):"
        grep -v '\.git' "$OUTPUT_FILE" || echo "No matches found."

      - name: Fail if obfuscation detected
        if: steps.scan.outcome == 'success' && steps.scan.outputs.stdout != ''
        run: |
          echo "::error ::Obfuscated (Base64) code detected by YARA. Please review the matches above."
          exit 1