name: YARA Obfuscation Scan

on:
  workflow_dispatch:
#  repository_dispatch:
#    types: [yara-scan]

jobs:
  yara-scan:
    name: Scan for Obfuscated (Base64) Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install YARA
        run: |
          sudo apt-get update
          sudo apt-get install -y yara

      - name: Run YARA scan and fail on match (excluding .git)
        id: scan
        run: |
          yara -w -r yara_rules/base64_obfuscation.yar . > results.txt
          echo "Filtered YARA scan results (excluding .git):"
          grep -v ".git" results.txt || true

          # Check if any lines remain after filtering
          MATCHES=$(grep -v ".git" results.txt | wc -l)
          if [ "$MATCHES" -gt 0 ]; then
            echo "YARA scan detected obfuscated code!"
            grep -v ".git" results.txt
            exit 1
          else
            echo "No obfuscated code detected."
          fi
